### ISSUE TITLE
Конструктор допускает создание аккаунта с отрицательным начальным балансом

### ISSUE THREAD

**Issue by alexialix** [alexialix/javaqa-team-diplom-2#11]
## Описание
Отсутствие валидации отрицательного начального баланса.
## Локация дефекта
https://github.com/alexialix/javaqa-team-diplom-2/blob/6db2e994412ac6242b46fc086108e1af0f9e139b/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L25

## Шаги воспроизведения
1. Открыть [код программы теста](https://github.com/alexialix/javaqa-team-diplom-2/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать объект класса CreditAccount с балансом -1000, кредитным лимитом 5000 и ставкой 20
3. Посмотреть результат

**Ожидаемы результат:** Система не позволяет создать аккаунт с отрицательным начальным балансом
**Фактический результат:** Система создает аккаунт с отрицательным начальным балансом

## Тест

https://github.com/alexialix/javaqa-team-diplom-2/blob/b2de094589a7837d657e43c53008c4fdb3a20d6a/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L31
## Окружение

- Операционная система: Windows 11 23H2
- IDEA IntelliJ IDEA 2024.2.1 (Community Edition)
- Java OpenJDK 11

**Comment by BigArtur116** [comment]
FIx bag
