### ISSUE TITLE
Система не позволяет создание кредитного счёта с нулевой ставкой 

### ISSUE THREAD

**Issue by alexialix** [alexialix/javaqa-team-diplom-2#14]
## Описание
Конструктор не выбрасывает исключение при создании аккаунта с нулевым кредитным лимитом
## Локация дефекта
https://github.com/alexialix/javaqa-team-diplom-2/blob/1757666b2551486801ded4ae6b2c87cd4d2d54c3/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L21
## Шаги воспроизведения
1. Создать объект CreditAccount с начальным балансом 0 и кредитным лимитом 0, ставкой 0
3. Посмотреть результат

**Ожидаемы результат:** Система не может создать аккаунт с нулевым кредитным лимитом
**Фактический результат:**  Система допускает нулевой кредитный лимит

## Тест
https://github.com/alexialix/javaqa-team-diplom-2/blob/1757666b2551486801ded4ae6b2c87cd4d2d54c3/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L19
## Окружение

- Операционная система: Windows 11 23H2
- IDEA IntelliJ IDEA 2024.2.1 (Community Edition)
- Java OpenJDK 11

**Comment by BigArtur116** [comment]
Fixed bug
