### ISSUE TITLE
При успешной оплате баланс присваивает отрицательную сумму, равную платежу

### ISSUE THREAD

**Issue by alexialix** [alexialix/javaqa-team-diplom-2#2]
## Описание
При выполнении метода с валидной суммой оплаты происходит невалидное переприсваивание баланса, что приводит к отрицательному значению суммы оплаты

## Локация дефекта
https://github.com/alexialix/javaqa-team-diplom-2/blob/361dd2ea93609975395ac630f99c2766d321872e/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L46

## Шаги воспроизведения
1. Открыть [код программы теста](https://github.com/alexialix/javaqa-team-diplom-2/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать объект класса CreditAccount с балансом 1000, кредитным лимитом 5000 и ставкой 15
3. Выполнить платёж на 3000 рублей
4. Проверить результат.

**Ожидаемы результат:** Баланс должен уменьшиться на 3000, новый баланс равен -2000.
**Фактический результат:**  Баланс присваивает сумму платежа с отрицательным значением, равным -3000

## Тест
https://github.com/alexialix/javaqa-team-diplom-2/blob/b2de094589a7837d657e43c53008c4fdb3a20d6a/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L58

## Окружение

- Операционная система: Windows 11 23H2
- IDEA IntelliJ IDEA 2024.2.1 (Community Edition)
- Java OpenJDK 11

**Comment by BigArtur116** [comment]
Баг исправлен
