### ISSUE TITLE
Система отклоняет оплату, равную кредитному лимиту при нулевом начальном балансе 

### ISSUE THREAD

**Issue by alexialix** [alexialix/javaqa-team-diplom-2#7]
## Описание
Платеж на сумму, равную кредитному лимиту, отклоняется, несмотря на то, что баланс остается в допустимых пределах.

## Локация дефекта
https://github.com/alexialix/javaqa-team-diplom-2/blob/6db2e994412ac6242b46fc086108e1af0f9e139b/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L45

## Шаги воспроизведения
1. Открыть [код программы теста](https://github.com/alexialix/javaqa-team-diplom-2/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать объект класса CreditAccount с балансом 0, кредитным лимитом 5000 и ставкой 15
3. Выполнить платёж на 5000 рублей
4. Посмотреть результат.

**Ожидаемы результат:**  Платёж проходит, баланс становится равным -5000
**Фактический результат:**  Платёж отклонён, баланс остается равным 0
## Тест
https://github.com/alexialix/javaqa-team-diplom-2/blob/b2de094589a7837d657e43c53008c4fdb3a20d6a/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L48

## Окружение

- Операционная система: Windows 11 23H2
- IDEA IntelliJ IDEA 2024.2.1 (Community Edition)
- Java OpenJDK 11

**Comment by BigArtur116** [comment]
Bug fixed
