### ISSUE TITLE
При пополнении баланса, система заменяет баланс суммой пополнения

### ISSUE THREAD

**Issue by alexialix** [alexialix/javaqa-team-diplom-2#8]
## Описание
Метод add заменяет баланс значением пополнения, вместо того чтобы прибавить его к текущему балансу.

## Локация дефекта
https://github.com/alexialix/javaqa-team-diplom-2/blob/6db2e994412ac6242b46fc086108e1af0f9e139b/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L69

## Шаги воспроизведения
1. Создать объект CreditAccount с начальным балансом 100 и кредитным лимитом 500, ставкой 15
2. Вызвать метод `add(200)`
3. Посмотреть результат

**Ожидаемы результат:** Пополнение баланса на 300
**Фактический результат:**  Баланс остается равным 200

## Тест
https://github.com/alexialix/javaqa-team-diplom-2/blob/3ed0a6c54569069fd683fe7dc1fc5d8f75a439f5/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L123
## Окружение

- Операционная система: Windows 11 23H2
- IDEA IntelliJ IDEA 2024.2.1 (Community Edition)
- Java OpenJDK 11

**Comment by BigArtur116** [comment]
Баг пофиксен
