### ISSUE TITLE
Отсутствие валидации начального баланса для расчета процентов 

### ISSUE THREAD

**Issue by alexialix** [alexialix/javaqa-team-diplom-2#9]
## Описание
 Метод yearChange начисляет проценты независимо от значения баланса.

## Локация дефекта
https://github.com/alexialix/javaqa-team-diplom-2/blob/6db2e994412ac6242b46fc086108e1af0f9e139b/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L83

## Шаги воспроизведения
1. Открыть [код программы теста](https://github.com/alexialix/javaqa-team-diplom-2/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать объект класса CreditAccount с балансом 200, кредитным лимитом 5000 и ставкой 15
3. Выполнить расчёт процентов
4. Проверить результат.

**Ожидаемы результат:** Сообщение о том, что процент не может быть рассчитан при положительном балансе или 0 
**Фактический результат:** Вывод процентного значения, отличного от 0
## Тест
https://github.com/alexialix/javaqa-team-diplom-2/blob/b2de094589a7837d657e43c53008c4fdb3a20d6a/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L170
## Окружение

- Операционная система: Windows 11 23H2
- IDEA IntelliJ IDEA 2024.2.1 (Community Edition)
- Java OpenJDK 11

**Comment by BigArtur116** [comment]
bug fixed
